name: Build & publish kodux
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Publish kodux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check
        run:
          gradle -si --no-daemon -Pversion=${GITHUB_REF:11} check
      - name: Publish
        run: |
          gradle -si --no-daemon -Pversion=${GITHUB_REF:11} publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
