name: Build & publish kodux
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Publish kodux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s --no-daemon -Pversion=${GITHUB_REF:11} check
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s --no-daemon -Pversion=${GITHUB_REF:11} publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
